#!/bin/bash
docker run -d -P --name ITWeb fursion/itwebservice:1.1.0
docker cp ITWeb:/etc/ITWebService /var/ITWebService
docker rm -f ITWeb
docker run -d -P --name ITWebService --network mynet -v /var/ITWebService:/etc/ITWebService  fursion/itwebservice:1.1.0